### ISSUE TITLE
Early Bird 1.11.2 Test - Chrash on assignVanillaBiomeTextures

### ISSUE THREAD

**Issue by Blackskyliner** [Hunternif/AntiqueAtlas#112]
I just compiled and tried your current 1.11.2 Version in my modded Minecraft.
I thought I'd share the crash so it's known. As the Travis Build just builds, but does not check for actual functionallity of the mod.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Default Options (DefaultOptions_1.11.2-8.2.2.jar)
  AppleCore (AppleCore-mc1.11.2-2.1.2.jar)
  ForgelinPlugin (Forgelin-1.4.0.jar)
  RebornCoreASM (RebornCore-1.11.2-2.13.5.42-universal.jar)
  LoadingPlugin (Quark-r1.2-87.jar)
  CoreMod (Aroma1997Core-1.11.2-1.2.0.0.b81.jar)
  CorePlugin (FluxedRedstone-2.6.0.54.jar)
  llibrary (llibrary-1.7.4-1.11.2.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.3.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-78.jar)
  literalascension (literalascension-1.11.2-1.0.1.1.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.1-anarchy.jar)
  LoadingPlugin (ResourceLoader-MC1.11-1.5.1.jar)
  ChiselCorePlugin (Chisel-MC1.11.2-0.0.9.11.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 3/19/17 7:49 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Antique Atlas (antiqueatlas)
Caused by: java.lang.NoSuchFieldError: OCEAN
	at hunternif.mc.atlas.ClientProxy.assignVanillaBiomeTextures(ClientProxy.java:247)
	at hunternif.mc.atlas.ClientProxy.preInit(ClientProxy.java:85)
	at hunternif.mc.atlas.AntiqueAtlasMod.preInit(AntiqueAtlasMod.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:641)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:246)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:647)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:275)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:440)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Linux (amd64) version 4.4.52-1-lts-custom
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 340284232 bytes (324 MB) / 871747584 bytes (831 MB) up to 6429081600 bytes (6131 MB)
	JVM Flags: 5 total; -Xmx6G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2259 Optifine OptiFine_1.11.2_HD_U_B7 131 mods loaded, 131 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2259.jar) 
	UCH	forge{13.20.0.2259} [Minecraft Forge] (forge-1.11.2-13.20.0.2259.jar) 
	UCH	aroma1997core{${version}} [Aroma1997Core] (Aroma1997Core-1.11.2-1.2.0.0.b81.jar) 
	UCH	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCH	achunkloader{1.11-1.2.0} [A Chunk Loader] (achunkloader-1.11.2-1.2.0.jar) 
	UCH	actuallyadditions{1.11.2-r106} [Actually Additions] (ActuallyAdditions-1.11.2-r106.jar) 
	UCH	akashictome{1.1-7} [Akashic Tome] (AkashicTome-1.1-7.jar) 
	UCH	alltheblocks{1.11.2-1.1.0} [All the Blocks] (alltheblocks-1.11.2-1.1.0.jar) 
	UCE	antiqueatlas{4.3.0} [Antique Atlas] (antiqueatlas-1.11.2-4.3.0-deobf.jar) 
	UCE	antiqueatlasoverlay{1.2} [antiqueatlasoverlay] (antiqueatlas-1.11.2-4.3.0-deobf.jar) 
	UCH	applecore{2.1.2} [AppleCore] (AppleCore-mc1.11.2-2.1.2.jar) 
	UCH	jei{4.2.10.248} [Just Enough Items] (jei_1.11.2-4.2.10.248.jar) 
	UCH	appleskin{1.0.6} [AppleSkin] (AppleSkin-mc1.11-1.0.6.jar) 
	UCH	baubles{1.4.3} [Baubles] (Baubles-1.11-1.4.3.jar) 
	UCH	forgelin{1.4.0} [Forgelin] (Forgelin-1.4.0.jar) 
	UCH	thedragonlib{1.11.2-3.1.1} [TheDragonLib] (thedragonlib-1.11.2-3.1.1.jar) 
	UCH	armorplus{1.11.2-10.1.2.3} [ArmorPlus] (armorplus-1.11.2-10.1.2.3.jar) 
	UCH	aroma1997corehelper{1.0} [Aroma1997Core|Helper] (Aroma1997Core-1.11.2-1.2.0.0.b81.jar) 
	UCH	aromabackup{1.0} [AromaBackup] (AromaBackup-1.11-2.1.0.0.b64.jar) 
	UCH	aromabackuprecovery{1.0} [AromaBackupRecovery] (AromaBackup-1.11-2.1.0.0.b64.jar) 
	UCH	astralsorcery{1.2.2-beta} [Astral Sorcery] (astralsorcery-1.2.2-beta.jar) 
	UCH	atg{2} [Alternate Terrain Generation] (atg-1.11.2-2.0.1.jar) 
	UCH	morphtool{1.1-13} [Morph-o-Tool] (Morph-o-Tool-1.1-13.jar) 
	UCH	psi{r1.1-46} [Psi] (Psi-r1.1-46.jar) 
	UCH	quark{r1.2-87} [Quark] (Quark-r1.2-87.jar) 
	UCH	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCH	babyanimals{1.11} [Baby Animals Model Swapper] (BabyAnimals-1.11.jar) 
	UCH	bdlib{1.13.2.7} [BD Lib] (bdlib-1.13.2.7-mc1.11.2.jar) 
	UCH	bedbugs{@VERSION@} [Bed Bugs] (BedBugs-1.11.2-1.1.6.jar) 
	UCH	betterachievements{0.4.3.12} [Better Achievements] (BetterAchievements-1.11.2-0.4.3.12.jar) 
	UCH	betterbuilderswands{0.11.0} [Better Builder's Wands] (BetterBuildersWands-1.11-0.11.0.233 4d933ac.jar) 
	UCH	biomesoplenty{6.0.2.2168} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.0.2.2168-universal.jar) 
	UCH	mobtotems{1.11.2-0.3.0} [Mob Totems] (mobtotems-1.11.2-0.3.0.jar) 
	UCH	theoneprobe{1.4.4} [The One Probe] (theoneprobe-1.1x-1.4.4.jar) 
	UCH	modularrouters{1.11.2-2.1.1} [Modular Routers] (modular-routers-1.11.2-2.1.1.jar) 
	UCH	guideapi{1.11-2.1.0-50} [Guide-API] (Guide-API-1.11-2.1.0-50.jar) 
	UCH	bloodmagic{1.11-2.1.7-76} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.11-2.1.7-76.jar) 
	UCH	botania{r1.9-342} [Botania] (Botania r1.9-342.jar) 
	UCH	chameleon{1.11-3.0.2} [Chameleon] (Chameleon-1.11-3.0.2.jar) 
	UCH	charsetlib{0.4.0-pre10} [‽] (Charset-mc1.11.2-0.4.0-pre10-c0faa4f8bd454f5f.jar) 
	UCH	charsetpipes{0.4.0-pre10} [|] (Charset-mc1.11.2-0.4.0-pre10-c0faa4f8bd454f5f.jar) 
	UCH	charsettweaks{0.4.0-pre10} [*] (Charset-mc1.11.2-0.4.0-pre10-c0faa4f8bd454f5f.jar) 
	UCH	charsetstorage{0.4.0-pre10} [■] (Charset-mc1.11.2-0.4.0-pre10-c0faa4f8bd454f5f.jar) 
	UCH	charsetcarts{0.4.0-pre10} [∐] (Charset-mc1.11.2-0.4.0-pre10-c0faa4f8bd454f5f.jar) 
	UCH	charsetcrafting{0.4.0-pre10} [#] (Charset-mc1.11.2-0.4.0-pre10-c0faa4f8bd454f5f.jar) 
	UCH	charsetdecoration{0.4.0-pre10} [^] (Charset-mc1.11.2-0.4.0-pre10-c0faa4f8bd454f5f.jar) 
	UCH	charsetwrench{0.4.0-pre10} [/] (Charset-mc1.11.2-0.4.0-pre10-c0faa4f8bd454f5f.jar) 
	UCH	chisel{MC1.11.2-0.0.9.11} [Chisel] (Chisel-MC1.11.2-0.0.9.11.jar) 
	UCH	chiselsandbits{13.10} [Chisels & Bits] (chiselsandbits-13.10.jar) 
	UCH	cyclopscore{0.9.4} [Cyclops Core] (CyclopsCore-1.11.2-0.9.4.jar) 
	UCH	colossalchests{1.5.0} [Colossal Chests] (ColossalChests-1.11.2-1.5.0.jar) 
	UCH	cookingforblockheads{5.3.13} [Cooking for Blockheads] (CookingForBlockheads_1.11.2-5.3.13.jar) 
	UCH	cosmeticarmorreworked{1.11.2-v1a} [CosmeticArmorReworked] (CosmeticArmorReworked-1.11.2-v1a.jar) 
	UCH	crafttweakerjei{1.0.1} [CraftTweaker JEI Support] (CraftTweaker-1.11.2-3.0.24.jar) 
	UCH	crafttweaker{3.0.24} [Crafttweaker] (CraftTweaker-1.11.2-3.0.24.jar) 
	UCH	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.11.2-3.0.24.jar) 
	UCH	custommainmenu{2.0.3} [Custom Main Menu] (CustomMainMenu-MC1.11-2.0.3.jar) 
	UCH	cyclicmagic{1.2.0} [Cyclic] (Cyclic-1.11.2-1.2.0.jar) 
	UCH	d3core{1.3.0.65} [D³Core] (D3Core-1.11.2-1.3.0.65.jar) 
	UCH	forestry{5.3.2.60} [Forestry] (forestry_1.11.2-5.3.2.60.jar) 
	UCH	eleccore{1.7.409} [ElecCore] (ElecCore-1.11-1.7.409.jar) 
	UCH	deepresonance{1.4.6} [DeepResonance] (deepresonance-1.1x-1.4.6.jar) 
	UCH	defaultoptions{8.2.2} [Default Options] (DefaultOptions_1.11.2-8.2.2.jar) 
	UCH	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod-1.11.2-1.3.0.jar) 
	UCH	embers{0.205} [Embers] (embers-0.205.jar) 
	UCH	shetiphiancore{3.4.3} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.3.jar) 
	UCH	endertanks{1.5.3} [EnderTanks] (endertanks-1.11.0-1.5.3.jar) 
	UCH	enderthing{0.7.3} [Enderthing] (enderthing-1.11.0-0.7.3.jar) 
	UCH	valkyrielib{1.11.2-0.11.0b} [Valkyrie Lib] (valkyrielib-1.11.2-0.11.0c.jar) 
	UCH	environmentaltech{1.11.2-0.11.0d} [Environmental Tech] (environmentaltech-1.11.2-0.11.0d.jar) 
	UCH	shadowmc{3.7.1} [ShadowMC] (ShadowMC-1.11.2-3.7.5.jar) 
	UCH	extrarails{1.2.1} [Extra Rails] (ExtraRails-1.11-1.2.1.jar) 
	UCH	extrautils2{1.0} [extrautils2] (extrautils2-1.11.2-1.3.3.jar) 
	UCH	zerocore{1.11.2-0.1.0.4} [Zero CORE] (zerocore-1.11.2-0.1.0.4.jar) 
	UCH	bigreactors{1.11.2-0.4.5.27} [Extreme Reactors] (ExtremeReactors-1.11.2-0.4.5.27.jar) 
	UCH	fastleafdecay{v12} [Fast Leaf Decay] (FastLeafDecay-v12.jar) 
	UCH	flatcoloredblocks{mc1.11-5.1} [Flat Colored Blocks] (flatcoloredblocks-mc1.11-5.1.jar) 
	UCH	reborncore{2.13.5.42} [RebornCore] (RebornCore-1.11.2-2.13.5.42-universal.jar) 
	UCH	reborncore-mcmultipart{2.13.5.42} [reborncore-MCMultiPart] (RebornCore-1.11.2-2.13.5.42-universal.jar) 
	UCH	fluxedredstone{@MODVERSION@} [FluxedRedstone] (FluxedRedstone-2.6.0.54.jar) 
	UCH	foamfix{@VERSION@} [FoamFix] (foamfix-0.6.1-anarchy.jar) 
	UCH	gendustry{1.6.5.7} [GenDustry] (gendustry-1.6.5.7-mc1.11.2.jar) 
	UCH	pressure{1.3.1.5} [Pressure Pipes] (pressure-1.3.1.5-mc1.11.2.jar) 
	UCH	advgenerators{0.9.20.5} [Advanced Generators] (generators-0.9.20.5-mc1.11.2.jar) 
	UCH	gravestone{1.7.2} [Gravestone] (GraveStone Mod 1.7.2.jar) 
	UCH	infernalmobs{1.7.2} [Infernal Mobs] (InfernalMobs-1.11.2.jar) 
	UCH	intwheel{1.2.4} [Interaction Wheel] (intwheel-1.1x-1.2.4.jar) 
	UCH	inventorytweaks{1.62-dev-78-e073cca} [Inventory Tweaks] (InventoryTweaks-1.62-dev-78.jar) 
	UCH	ironchest{1.11.2-7.0.18.800} [Iron Chest] (ironchest-1.11.2-7.0.18.800.jar) 
	UCH	itemscroller{0.11.0} [Item Scroller] (itemscroller-1.11.2-0.11.0.jar) 
	UCH	jeibees{0.9.0.5} [JEI Bees] (jeibees-0.9.0.5-mc1.11.2.jar) 
	UCH	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UCH	je_calculation{1.11.2-2.6.2} [Just Enough Calculation] (JustEnoughCalculation-1.11.2-2.6.2.jar) 
	UCH	jeresources{0.6.3.4} [Just Enough Resources] (JustEnoughResources-1.11.2-0.6.3.4.jar) 
	UCH	llibrary{1.7.4} [LLibrary] (llibrary-1.7.4-1.11.2.jar) 
	UCH	literalascension{1.11.2-1.0.1.1} [Literal Ascension] (literalascension-1.11.2-1.0.1.1.jar) 
	UCH	llor{1.1.3-mc1.11.2} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.3-mc1.11.2.jar) 
	UCH	lumberjack{1.0} [lumberjack] (Lumberjack-1.11.2-1.3.1.48.jar) 
	UCH	modnametooltip{1.7.0} [Mod Name Tooltip] (modnametooltip_1.11-1.7.0.jar) 
	UCH	morpheus{1.11.2-3.2.13} [Morpheus] (Morpheus-1.11.2-3.2.13.jar) 
	UCH	mysteriousmiscellany{1.11.2-1.1.3} [Mysterious Miscellany] (MysteriousMiscellany-1.11.2-1.1.3.jar) 
	UCH	mysticalagriculture{1.4.4} [Mystical Agriculture] (mysticalagriculture[1.11.2]-1.4.4a.jar) 
	UCH	netherportalfix{1.0} [NetherPortalFix] (NetherPortalFix_1.11-4.3.1.jar) 
	UCH	nmsot{1.2.0-mc1.11.2} [No Mob Spawning on Trees] (NoMobSpawningOnTrees-1.2.0-mc1.11.2.jar) 
	UCH	recipehandler{0.6} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.6(1.11).jar) 
	UCH	notenoughwands{1.5.4} [Not Enough Wands] (notenoughwands-1.1x-1.5.4.jar) 
	UCH	packetfilter{1.4.0} [Packet Filter] (packetfilter-1.5.0.jar) 
	UCH	harvestcraft{1.11.2f} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2f.jar) 
	UCH	placeableitems{3.0.3.1} [Placeable Items Mod] (placeableitems-3.0.3.1.jar) 
	UCH	platforms{1.3.3} [Platforms] (platforms-1.11.0-1.3.3.jar) 
	UCH	rangedpumps{0.4} [Ranged Pumps] (rangedpumps-0.4.jar) 
	UCH	refinedstorage{1.4.1} [Refined Storage] (refinedstorage-1.4.1.jar) 
	UCH	xreliquary{1.11.2-1.3.3.635} [Reliquary] (Reliquary-1.11.2-1.3.3.635.jar) 
	UCH	resourceloader{1.5.1} [Resource Loader] (ResourceLoader-MC1.11-1.5.1.jar) 
	UCH	rftools{5.88} [RFTools] (rftools-1.1x-5.88.jar) 
	UCH	rftoolscontrol{1.6.6} [RFTools Control] (rftoolsctrl-1.1x-1.6.6.jar) 
	UCH	rftoolsdim{4.55} [RFTools Dimensions] (rftoolsdim-1.1x-4.55.jar) 
	UCH	roguelike{1.6.6} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.6.jar) 
	UCH	roots{0.014} [Roots 2] (roots-2-0.014.jar) 
	UCH	simplegenerators{1.11.2-0.11.0a} [Simple Generators] (simplegenerators-1.11.2-0.11.0a.jar) 
	UCH	simplyconveyors{2.1.0} [Simply Conveyors] (SimplyConveyors-2.1.2.jar) 
	UCH	soulshardstow{1.11-2.6.6-47} [Soul Shards - The Old Ways] (SoulShards-TOW-1.11-2.6.6-47.jar) 
	UCH	spartanshields{1.2a} [Spartan Shields] (SpartanShields-1.11-1.2a.jar) 
	UCH	spiceoflife{1.3.8} [The Spice of Life] (SpiceOfLife-mc1.11.2-1.3.8.jar) 
	UCH	storagedrawers{1.11.2-4.2.0} [Storage Drawers] (StorageDrawers-1.11.2-4.2.0.jar) 
	UCH	techreborn{2.1.10.88} [TechReborn] (TechReborn-1.11.2-2.1.10.88-universal.jar) 
	UCH	terraqueous{1.3.8} [Terraqueous] (terraqueous-1.11.0-1.3.8.jar) 
	UCH	xnet{1.1.0} [XNet] (xnet-1.1.0.jar) 
	Loaded coremods (and transformers): 
Default Options (DefaultOptions_1.11.2-8.2.2.jar)
  net.blay09.mods.defaultoptions.coremod.DefaultOptionsClassTransformer
AppleCore (AppleCore-mc1.11.2-2.1.2.jar)
  squeek.applecore.asm.TransformerModuleHandler
ForgelinPlugin (Forgelin-1.4.0.jar)
  
RebornCoreASM (RebornCore-1.11.2-2.13.5.42-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
LoadingPlugin (Quark-r1.2-87.jar)
  vazkii.quark.base.asm.ClassTransformer
CoreMod (Aroma1997Core-1.11.2-1.2.0.0.b81.jar)
  
CorePlugin (FluxedRedstone-2.6.0.54.jar)
  
llibrary (llibrary-1.7.4-1.11.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.3.jar)
  shetiphian.core.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.62-dev-78.jar)
  invtweaks.forge.asm.ContainerTransformer
literalascension (literalascension-1.11.2-1.0.1.1.jar)
  com.jamieswhiteshirt.literalascension.core.patcher.LiteralAscensionRuntimePatcher
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.1-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
LoadingPlugin (ResourceLoader-MC1.11-1.5.1.jar)
  lumien.resourceloader.asm.ClassTransformer
ChiselCorePlugin (Chisel-MC1.11.2-0.0.9.11.jar)
  team.chisel.common.asm.ChiselTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 378.13' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	List of loaded APIs: 
		* actuallyadditionsapi (33) from ActuallyAdditions-1.11.2-r106.jar
		* antiqueatlasapi (5.1) from antiqueatlas-1.11.2-4.3.0-deobf.jar
		* AppleCoreAPI (2.2.0) from AppleCore-mc1.11.2-2.1.2.jar
		* ArmorPlusApi (2.0) from armorplus-1.11.2-10.1.2.3.jar
		* AromaBackupAPI (1.0) from AromaBackup-1.11-2.1.0.0.b64.jar
		* Baubles|API (1.4.0.2) from Baubles-1.11-1.4.3.jar
		* BetterAchievements|API (0.4.3.12) from BetterAchievements-1.11.2-0.4.3.12.jar
		* bigreactors|API (4.0.1) from ExtremeReactors-1.11.2-0.4.5.27.jar
		* bloodmagic|API (1.11-2.1.7-76) from BloodMagic-1.11-2.1.7-76.jar
		* BotaniaAPI (86) from Botania r1.9-342.jar
		* CharsetAPI (0.1) from Charset-mc1.11.2-0.4.0-pre10-c0faa4f8bd454f5f.jar
		* CharsetAPI|Audio (0.0) from Charset-mc1.11.2-0.4.0-pre10-c0faa4f8bd454f5f.jar
		* CharsetAPI|Lib (0.2) from Charset-mc1.11.2-0.4.0-pre10-c0faa4f8bd454f5f.jar
		* CharsetAPI|Pipes (0.3) from Charset-mc1.11.2-0.4.0-pre10-c0faa4f8bd454f5f.jar
		* CharsetAPI|Storage (0.1) from Charset-mc1.11.2-0.4.0-pre10-c0faa4f8bd454f5f.jar
		* CharsetAPI|Tape (0.0) from Charset-mc1.11.2-0.4.0-pre10-c0faa4f8bd454f5f.jar
		* CharsetAPI|Wires (0.3) from Charset-mc1.11.2-0.4.0-pre10-c0faa4f8bd454f5f.jar
		* ChiselAPI (0.0.1) from Chisel-MC1.11.2-0.0.9.11.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.11.2-0.0.9.11.jar
		* ChiselsAndBitsAPI (13.8.0) from chiselsandbits-13.10.jar
		* CoFHAPI (1.8.9R1.2.0B1) from mcjtylib-1.1x-2.3.10.jar
		* cofhapi (1.4.0) from extrautils2-1.11.2-1.3.3.jar
		* CoFHAPI|block (1.8.9R1.2.0B1) from zerocore-1.11.2-0.1.0.4.jar
		* CoFHAPI|core (1.8.9R1.2.0B1) from zerocore-1.11.2-0.1.0.4.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from theoneprobe-1.1x-1.4.4.jar
		* cofhapi|energy (1.4.0) from extrautils2-1.11.2-1.3.3.jar
		* CoFHAPI|inventory (1.8.9R1.2.0B1) from zerocore-1.11.2-0.1.0.4.jar
		* CoFHAPI|item (1.8.9R1.2.0B1) from mcjtylib-1.1x-2.3.10.jar
		* CoFHAPI|tileentity (1.8.9R1.2.0B1) from zerocore-1.11.2-0.1.0.4.jar
		* CoFHAPI|transport (1.8.9R1.2.0B1) from zerocore-1.11.2-0.1.0.4.jar
		* compatlayer (0.2.2) from compatlayer-1.11.2-0.2.2.jar
		* DR-API (1.0.4-Beta) from deepresonance-1.1x-1.4.6.jar
		* ElecCoreAPI (1.0) from ElecCore-1.11-1.7.409.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.11-1.7.409.jar
		* environmentaltech-api (1.11.2-0.11.0d) from environmentaltech-1.11.2-0.11.0d.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.11.2-5.3.2.60.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.11.2-5.3.2.60.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.11.2-5.3.2.60.jar
		* ForestryAPI|climate (2.1.0) from forestry_1.11.2-5.3.2.60.jar
		* ForestryAPI|core (5.1.0) from forestry_1.11.2-5.3.2.60.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.11.2-5.3.2.60.jar
		* ForestryAPI|food (1.1.0) from forestry_1.11.2-5.3.2.60.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.11.2-5.3.2.60.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.11.2-5.3.2.60.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.11.2-5.3.2.60.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.11.2-5.3.2.60.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.11.2-5.3.2.60.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.11.2-5.3.2.60.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.11.2-5.3.2.60.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.11.2-5.3.2.60.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.11.2-5.3.2.60.jar
		* ForestryAPI|world (2.1.0) from forestry_1.11.2-5.3.2.60.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.5.7-mc1.11.2.jar
		* Guide-API|API (1.11-2.1.0-50) from Guide-API-1.11-2.1.0-50.jar
		* intwheel_api (1.2.4) from intwheel-1.1x-1.2.4.jar
		* jeresources|API (0.6.3.4) from JustEnoughResources-1.11.2-0.6.3.4.jar
		* journeymap|client-api (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-display (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-event (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-model (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-util (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* JustEnoughItemsAPI (4.11.0) from jei_1.11.2-4.2.10.248.jar
		* mcjtylib_ng (2.3.10) from mcjtylib-1.1x-2.3.10.jar
		* pressureAPI (1.3.1.5) from pressure-1.3.1.5-mc1.11.2.jar
		* PsiAPI (4) from Psi-r1.1-46.jar
		* reborncoreAPI (2.13.5.42) from RebornCore-1.11.2-2.13.5.42-universal.jar
		* reborncoreAPI|Fuel (2.13.5.42) from RebornCore-1.11.2-2.13.5.42-universal.jar
		* reborncoreAPI|Power (2.13.5.42) from RebornCore-1.11.2-2.13.5.42-universal.jar
		* reborncoreAPI|Recipe (2.13.5.42) from RebornCore-1.11.2-2.13.5.42-universal.jar
		* reborncoreAPI|Tile (2.13.5.42) from RebornCore-1.11.2-2.13.5.42-universal.jar
		* StorageDrawersAPI (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.0.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* StorageDrawersAPI|pack (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.0.jar
		* StorageDrawersAPI|registry (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.0.jar
		* StorageDrawersAPI|render (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.0.jar
		* StorageDrawersAPI|storage (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.0.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* techrebornAPI (2.1.10.88) from TechReborn-1.11.2-2.1.10.88-universal.jar
		* TerraqueousAPI (1.0) from terraqueous-1.11.0-1.3.8.jar
		* TerraqueousAPI|Cloud (1.0) from terraqueous-1.11.0-1.3.8.jar
		* TerraqueousAPI|Machines (1.0) from terraqueous-1.11.0-1.3.8.jar
		* TerraqueousAPI|Plant (1.0) from terraqueous-1.11.0-1.3.8.jar
		* theoneprobe_api (1.4.4) from theoneprobe-1.1x-1.4.4.jar
		* valkyrielib.api (1.11.2-0.11.0b) from valkyrielib-1.11.2-0.11.0c.jar
		* zerocore|API|multiblock (1.10.2-0.0.2) from zerocore-1.11.2-0.1.0.4.jar
		* zerocore|API|multiblock|rectangular (1.10.2-0.0.2) from zerocore-1.11.2-0.1.0.4.jar
		* zerocore|API|multiblock|validation (1.10.2-0.0.2) from zerocore-1.11.2-0.1.0.4.jar
	d3core: Debug: false Silliness: true AprilFools: true PastPost:false
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 2.13.5.42
		Mixin Status: 1
		Runtime Debofucsation 1
		RenderEngine: 1
	OptiFine Version: OptiFine_1.11.2_HD_U_B7
	Render Distance Chunks: 10
	Mipmaps: 2
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: kuda-shaders-v6.4.80.zip
	OpenGlVersion: 4.5.0 NVIDIA 378.13
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
```

**Comment by Blackskyliner** [comment]
nvm. After compilling with the actual forge version  of my installation/instance everything works fine. Also the bug was from using the wrong .jar ( never use the -deobf jar - silly me ;) )
