### ISSUE TITLE
[1.12.2] Crash when applying/loading Golrith's colored texture pack in game

### ISSUE THREAD

**Issue by armuell** [Hunternif/AntiqueAtlas#160]
Crash report (scroll to very bottom): https://pastebin.com/pcZdhpsh

**Comment by armuell** [comment]
After restarting MC the resource pack was applied and the mod ran fine but figured it was worth reporting

**Comment by tyra314** [comment]
The crash report doesn't mention AntiqueAtlas at all, why do you think, it is a problem with this mod?
Have you tried changing the texture pack without AntiqueAtlas being in the mod pack?

**Comment by armuell** [comment]
I was unable to reproduce the crash and it is totally possible the crash is related to vanilla/another mod but the reason I suspected it was antique atlas was because the stack trace in the pastebin I posted contained the words AtlasSprite and Map 

```
Stacktrace:
    at net.minecraft.client.renderer.texture.TextureAtlasSprite.func_147963_d(TextureAtlasSprite.java:314)
    at net.minecraft.client.renderer.texture.TextureMap.func_184397_a(TextureMap.java:300)
    at net.minecraft.client.renderer.texture.TextureMap.loadTexture(TextureMap.java:182)
    at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:110)
    at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:91)
    at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:168)
    at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:131)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
    at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:814)
    at net.minecraft.client.gui.GuiScreenResourcePacks.func_146284_a(SourceFile:133)
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
    at net.minecraft.client.gui.GuiScreenResourcePacks.func_73864_a(SourceFile:141)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
    at net.minecraft.client.gui.GuiScreenResourcePacks.func_146274_d(SourceFile:77)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by Kenkron** [comment]
I think this is more to do with a steal_merger.json file missing

```
java.lang.Exception: Could not load model definition for variant betterwithmods:steel_merger
    at net.minecraftforge.client.model.ModelLoader.func_177586_a(ModelLoader.java:266)
    at net.minecraft.client.renderer.block.model.ModelBakery.loadBlock(ModelBakery.java:121)
    at net.minecraftforge.client.model.ModelLoader.func_188640_b(ModelLoader.java:221)
    at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:159)
    at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.RuntimeException: Encountered an exception when loading model definition of model betterwithmods:blockstates/steel_merger.json
    at net.minecraft.client.renderer.block.model.ModelBakery.func_188632_a(ModelBakery.java:228)
    at net.minecraft.client.renderer.block.model.ModelBakery.func_177586_a(ModelBakery.java:208)
    at net.minecraftforge.client.model.ModelLoader.func_177586_a(ModelLoader.java:262)
    ... 14 more
Caused by: java.io.FileNotFoundException: betterwithmods:blockstates/steel_merger.json
    at net.minecraft.client.resources.FallbackResourceManager.func_135056_b(FallbackResourceManager.java:104)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_135056_b(SimpleReloadableResourceManager.java:79)
    at net.minecraft.client.renderer.block.model.ModelBakery.func_188632_a(ModelBakery.java:221)
    ... 16 more
```
