### ISSUE TITLE
4.4.8 Not Loading Custom Textures

### ISSUE THREAD

**Issue by SjetCraft** [Hunternif/AntiqueAtlas#183]
Antique Atlas Version: 1.12.2-4.4.8
Forge: 14.23.3.2655

On loading Minecraft the json files are overwritten with default values.
Followed the wiki to load custom textures/jsons and used Golrith's texture pack.

**Comment by Kenkron** [comment]
Earlyshooter has put work into fixing the biome ids for 1.12.2 [here](https://minecraft.curseforge.com/projects/antique-atlas?comment=108). I tested it yesterday, and it works (though it does say that the resource pack is for an older version of minecraft).

Golrith wants to update the textures for 1.12.2 and add additional mod support (https://minecraft.curseforge.com/projects/antique-atlas?comment=113).

**Comment by Kenkron** [comment]
In light of what Golrith has been saying, I might have been wrong about it working the other day. If you send me your files, maybe I can take a look.

**Comment by TheAtomicOption** [comment]
I've been trying to build a resource pack to add custom textures for the Antique Atlas for modded biomes in the SevTech modpack. (I was frustrated that every biome in The Betweenlands gets rendered as basic swamp.) I was finally able to get it working today. 

The issue was that I had some capital letters in the filenames of the texture images. Turns out it's not just the path but the *entire filename* that must be all lowercase in order to work correctly with v4.4.9 of Antique Atlas. 

Below is a log of what happens when my resource pack includes a file with the path/capitalization: `theatomicoption\textures\BL_CoarseIslands.png`

```
[16:28:55] [main/WARN]: Failed to load texture: theatomicoption:textures/bl_coarseislands.png
java.io.FileNotFoundException: theatomicoption:textures/bl_coarseislands.png
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:69) ~[cei.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65) ~[cev.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SimpleTexture.java:40) ~[cdm.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:90) [cdr.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:60) [cdr.class:?]
	at kenkron.antiqueatlasoverlay.SetTileRenderer.draw(SetTileRenderer.java:37) [SetTileRenderer.class:?]
	at kenkron.antiqueatlasoverlay.AAORenderEventReceiver.drawTiles(AAORenderEventReceiver.java:199) [AAORenderEventReceiver.class:?]
	at kenkron.antiqueatlasoverlay.AAORenderEventReceiver.drawMinimap(AAORenderEventReceiver.java:136) [AAORenderEventReceiver.class:?]
	at kenkron.antiqueatlasoverlay.AAORenderEventReceiver.eventHandler(AAORenderEventReceiver.java:117) [AAORenderEventReceiver.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_75_AAORenderEventReceiver_eventHandler_Post.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:911) [GuiIngameForge.class:?]
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:207) [GuiIngameForge.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1420) [buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_172]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

**Comment by tyra314** [comment]
There won't be another 1.12 update, so I'm closing this.
