### ISSUE TITLE
Error receiving packet antiqueatlas:dimension_update!

### ISSUE THREAD

**Issue by calloatti** [Hunternif/AntiqueAtlas#234]
I am getting a lot of these in the log:

MC 1.14.3
Fabric
antiqueatlas-5.0.6-fabric

```
[20:01:46] [Netty Local Client IO #3/WARN]: Error receiving packet antiqueatlas:dimension_update!
java.lang.IndexOutOfBoundsException: readerIndex(22) + length(8) exceeds writerIndex(22): UnpooledHeapByteBuf(ridx: 22, widx: 22, cap: 22)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1405) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1392) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:843) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at net.minecraft.class_2540.readBytes(class_2540.java:1071) ~[intermediary-minecraft-1.14.3-client.jar:?]
	at hunternif.mc.atlas.network.client.DimensionUpdatePacket.read(DimensionUpdatePacket.java:64) ~[antiqueatlas-5.0.6-fabric.jar:?]
	at hunternif.mc.atlas.network.PacketDispatcher.lambda$null$1(PacketDispatcher.java:73) ~[antiqueatlas-5.0.6-fabric.jar:?]
	at net.fabricmc.fabric.impl.network.PacketRegistryImpl.accept(PacketRegistryImpl.java:173) [098586e0-40ac-4f17-ac73-74b8f99cd36c.jar:?]
	at net.minecraft.class_634.handler$onCustomPayload$zzc000(class_634.java:2309) [intermediary-minecraft-1.14.3-client.jar:?]
	at net.minecraft.class_634.method_11152(class_634.java) [intermediary-minecraft-1.14.3-client.jar:?]
	at net.minecraft.class_2658.method_11457(class_2658.java:62) [intermediary-minecraft-1.14.3-client.jar:?]
	at net.minecraft.class_2658.method_11054(class_2658.java:10) [intermediary-minecraft-1.14.3-client.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:159) [intermediary-minecraft-1.14.3-client.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:150) [intermediary-minecraft-1.14.3-client.jar:?]
	at net.minecraft.class_2535.channelRead0(class_2535.java:54) [intermediary-minecraft-1.14.3-client.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:304) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:446) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:51) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:404) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by ghost** [comment]
I got these also as far back as 5.0.0-alpha.1 (asie's initial port) here is the github issue I created back for that version: https://github.com/asiekierka/AntiqueAtlas/issues/2 as far as I can tell this is produced when another player changes dimension.
