### ISSUE TITLE
Unstated dependency on Cotton mod

### ISSUE THREAD

**Issue by matthew-cline** [Hunternif/AntiqueAtlas#237]
The [Cotton](https://www.curseforge.com/minecraft/mc-mods/cotton) mod is needed for this mod to work, otherwise it [throws an exception](https://gist.github.com/matthew-cline/09ade8bc8f2bf963d8aa7c208b8a2e15).

**Comment by tyra314** [comment]
Fixed in 5.1.1-fabric

**Comment by koocotte** [comment]
I still have the exception with only antiqueatlas-5.1.1-fabric.jar and fabric-api-0.4.0+build.240-1.14.jar in the mods folder

```
Exception in thread "main" java.lang.RuntimeException: Failed to resolve mods!
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:159)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:122)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: net.fabricmc.loader.discovery.ModResolutionException: Could not resolve valid mod collection (at: antiqueatlas requires {cotton-config @ [>=1.0.0-rc.1]})
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:170)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:603)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:157)
	... 2 more

```

**Comment by TehNut** [comment]
Yes that's what it's supposed to say when you're missing the dependency
