### ISSUE TITLE
[Fabric] Crash on launch

### ISSUE THREAD

**Issue by BingRazer** [Hunternif/AntiqueAtlas#243]
Crashes on launch with Fabric loader 0.6.3 for both dedicated server and client. Tested with it as only mod installed.

```
Loading for game Minecraft 1.14.4
Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!
    at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:51)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
    at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:107)
    at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49)
Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
    at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:63)
    at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105)
    ... 1 more
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at
net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61)
    ... 2 more
Caused by: java.lang.RuntimeException: Failed to resolve mods!
    at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:159)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:122)
    at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26)
    ... 7 more
Caused by: net.fabricmc.loader.discovery.ModResolutionException: Errors were found!
 - Mod antiqueatlas depends on mod {fabric @ [>=0.4.0]}, which is missing!
 - Mod antiqueatlas depends on mod {cotton-config @ [>=1.0.0-rc.1]}, which is missing!
    at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:309)
    at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:603)
    at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:157)
    ... 9 more
```
Looks like this is the issue?
```Caused by: net.fabricmc.loader.discovery.ModResolutionException: Errors were found!
 - Mod antiqueatlas depends on mod {fabric @ [>=0.4.0]}, which is missing!
 - Mod antiqueatlas depends on mod {cotton-config @ [>=1.0.0-rc.1]}, which is missing!
```

**Comment by tyra314** [comment]
yeah. You’re missing other mods, which are a dependency. This is the fabric mod and the cotton mod
