### ISSUE TITLE
Antique Atlas fails to load into the game because of it's textures

### ISSUE THREAD

**Issue by InvitedRhino683** [Hunternif/AntiqueAtlas#292]
Whenever I add Antique Atlas to my modpack, it always gets stuck on the main menu. It loads, gets to the main menu, loads again, etc. I can't even do anything!

Here is the log:
[latest.log](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/5790012/latest.log)
 
Current options.txt:
[options.txt](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/5790014/options.txt)

Minecraft Version: 1.16.4

Antique Atlas Version: 5.4.0

Fabric Version: 0.10.8

**Comment by tyra314** [comment]
I don't see any error in the log file. How do you now ist the textures?

**Comment by InvitedRhino683** [comment]
Well, there is a bunch of "Missing texture" errors. So, I kind of assumed that was what caused the crash.

**Comment by mhrazor1** [comment]
I think I am having the same issue. Main menu fades in, then snaps back to loading screen, repeat. Here is my log and the part I think is relevant

[latest.log](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/files/5791264/latest.log)

java.util.concurrent.CompletionException: java.lang.RuntimeException: Attempted to register ID ResourceKey[antiqueatlas:marker / antiqueatlas:skull] at different raw IDs (0, 5)! If you're trying to override an item, use .set(), not .register()!
	at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.7) ~[?:?]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1621) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51]
Caused by: java.lang.RuntimeException: Attempted to register ID ResourceKey[antiqueatlas:marker / antiqueatlas:skull] at different raw IDs (0, 5)! If you're trying to override an item, use .set(), not .register()!
	at net.minecraft.util.registry.SimpleRegistry.handler$bjp000$setPre(SimpleRegistry:1150) ~[?:?]
	at net.minecraft.util.registry.SimpleRegistry.set(SimpleRegistry) ~[?:?]
	at net.minecraft.util.registry.SimpleRegistry.set(SimpleRegistry:72) ~[?:?]
	at net.minecraft.util.registry.DefaultedRegistry.set(DefaultedRegistry:28) ~[?:?]
	at hunternif.mc.impl.atlas.registry.MarkerType.register(MarkerType.java:57) ~[antiqueatlas-5.4.0-fabric.jar:?]
	at hunternif.mc.impl.atlas.marker.MarkerTextureConfig.lambda$apply$2(MarkerTextureConfig.java:72) ~[antiqueatlas-5.4.0-fabric.jar:?]
	at hunternif.mc.impl.atlas.marker.MarkerTextureConfig$$Lambda$7061/1850567095.run(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51]
	... 5 more
