### ISSUE TITLE
Mixin Config / Antiqueatlas 5.4.4 Forge

### ISSUE THREAD

**Issue by RainnMannx** [Hunternif/AntiqueAtlas#318]
[main/ERROR] [mixin/]: Mixin config antiqueatlas.mixins.json does not specify "minVersion" property
antiqueatlas-5.4.4-forge

Minor item just OCD on errors in the logs =P

**Comment by KirbyBrasse** [comment]
Hey i think i have that problem did you solve it ?

**Comment by tyra314** [comment]
This isn't a real problem. Just one message. If you have problems, it's not this one.

**Comment by aaronhowser1** [comment]
```
[16Jan2022 09:42:07.475] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:213]: Failed to start Minecraft:
[16Jan2022 09:42:07.477] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: java.lang.reflect.InvocationTargetException
[16Jan2022 09:42:07.477] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16Jan2022 09:42:07.478] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[16Jan2022 09:42:07.478] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16Jan2022 09:42:07.478] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[16Jan2022 09:42:07.479] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[16Jan2022 09:42:07.479] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[16Jan2022 09:42:07.479] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[16Jan2022 09:42:07.479] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[16Jan2022 09:42:07.480] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: Caused by: java.lang.reflect.InvocationTargetException
[16Jan2022 09:42:07.481] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16Jan2022 09:42:07.481] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[16Jan2022 09:42:07.481] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16Jan2022 09:42:07.481] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[16Jan2022 09:42:07.482] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
[16Jan2022 09:42:07.483] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	... 8 more
[16Jan2022 09:42:07.484] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: Caused by: java.lang.NoSuchMethodError: 'void sun.security.util.ManifestEntryVerifier.<init>(java.util.jar.Manifest)'
[16Jan2022 09:42:07.485] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.java:66)
[16Jan2022 09:42:07.486] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:275)
[16Jan2022 09:42:07.486] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[16Jan2022 09:42:07.486] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[16Jan2022 09:42:07.487] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[16Jan2022 09:42:07.487] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at java.base/java.lang.Class.forName0(Native Method)
[16Jan2022 09:42:07.488] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at java.base/java.lang.Class.forName(Class.java:467)
[16Jan2022 09:42:07.488] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:67)
[16Jan2022 09:42:07.489] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.loadConnectors(MixinConnectorManager.java:70)
[16Jan2022 09:42:07.490] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:59)
[16Jan2022 09:42:07.491] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:196)
[16Jan2022 09:42:07.491] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:202)
[16Jan2022 09:42:07.492] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:201)
[16Jan2022 09:42:07.492] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:195)
[16Jan2022 09:42:07.493] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97)
[16Jan2022 09:42:07.493] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
[16Jan2022 09:42:07.493] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97)
[16Jan2022 09:42:07.493] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
[16Jan2022 09:42:07.493] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[16Jan2022 09:42:07.494] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[16Jan2022 09:42:07.494] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[16Jan2022 09:42:07.494] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:659]: 	... 13 more
[16Jan2022 09:42:07.494] [main/INFO] [STDOUT/]: [org.multimc.EntryPoint:main:37]: Exiting with -1
```
It started instantly crashing here for me, possibly because I installed Java 17 so I could use 1.18?

Yep, aimed MultiMC back to using 8 and it works fine now.

**Comment by cykonetic** [comment]
I just updated my jre to:
Java is version 1.8.0_321, using 64-bit architecture, from Oracle Corporation.
Now I am getting this issue.

**Comment by zaxlofful** [comment]
Same, my docker image for Java 11 got updated and now I cannot run Minecraft anymore...WTF.

What can't ya'll just fix the regressions with the latest version of Java? Why do we have to run on such an old version, or at least figure it out...So that its stable

I am using Java 11, (which was just updated tonight) and I am no having this issue:

[05:20:20] [main/ERROR] [mixin/]: Mixin config antiqueatlas.mixins.json does not specify "minVersion" property

**Comment by tyra314** [comment]
Again, this "error" message:

> [05:20:20] [main/ERROR] [mixin/]: Mixin config antiqueatlas.mixins.json does not specify "minVersion" property

 is NOT the reason your minecraft is crashing.

Judging from the traceback provided by aaronhowser, it seems like you're using a JRE version that isn't supported by Forge itself. If you're running Minecraft 1.16 (or older), you should be using Java 8. For 1.17.x, you can use Java 16. For 1.18.x, you can use Java 17. These are the version, which vanilla uses and hence are the only supported ones.

**Comment by zaxlofful** [comment]
As of yestreday, that was the only issue "difference" between when Java updated and afterwards.

So I guess what we are trying to say, is something changed with how Java 11 works.....Literally yesterday and now my minecraft won't boot.

The ONLY thing that as changed was Java updating to the newest version of Java 11; which now doesn't work...THis is the only error that is listed.

So, now you are telling me that my game crashing is a lie?

It literally worked 5 seconds before updating to the latest version of Java 11...Since I am using containers there is no way to go back.

Just because you don't think the bug is worth fixing, doesn't mean its not a bug.

Just fix your code to include a "minVersion" and then no one will care anymore, including Java.

**Comment by tyra314** [comment]
I’m sorry, your game crashes and I understand that this is frustrating for you. But this not the place to unload it.

You need to carefully read again what I said. While the error message described here, is a bug, it does not cause crashes. Unfortunately, just because it is the last thing you see, does not necessarily mean, this has caused the issue. When someone opens a door directly in your face, the door isn’t cause, it just happens to be the last thing you see before the crash. 

Also, I didn’t say your crash is a lie. I’m just pointing out that this issue isn’t the cause of the crash. So regardless of me fixing it, it won’t fix your crash. 

This brings us to the core of the issue. You are running Java 11, but Minecraft (prior to 1.17) and hence all mods target Java 8. It is old, yes, but you cannot expect everything to work, if your using the wrong version. Don’t believe me? Look here: https://forums.minecraftforge.net/announcement/15-java-and-you-how-to-avoid-crashes/

One tangent point about containers. One of the core ideas of containers is their ability to easily rollback changes by just deploying the old image again. Also, there are the excellent docker images from itzg.

You still think I’m wrong? That is totally possible, but already the OP of this issue pointed out, that this report is only an OCD thing. Anyways, in that case you need to provide the server log and crash report.

**Comment by unhott** [comment]
@tyra314 thank you so much - this helped me resolve the same exact issue. Everything else was just making no sense! So glad I stumbled onto this eventually :)

**Comment by conner-s** [comment]
Going to comment this here since this is the first google result that pops up when searching for Create: Above and Beyond crashing issues since 

```
[main/ERROR] [mixin/]: Mixin config antiqueatlas.mixins.json does not specify "minVersion" property
antiqueatlas-5.4.4-forge
```
is the first error line that's thrown it's likely why it has been misdiagnosed as a Antique Atlas issue.


For this issue you either need to downgrade your Java 8 to something before update 321 or upgrade you Forge version to Forge 36.2.26 or greater.

[Found the fix here](https://github.com/McModLauncher/modlauncher/issues/91)

Hope this helps!

**Comment by zaxlofful** [comment]
> Going to comment this here since this is the first google result that pops up when searching for Create: Above and Beyond crashing issues since
> 
> ```
> [main/ERROR] [mixin/]: Mixin config antiqueatlas.mixins.json does not specify "minVersion" property
> antiqueatlas-5.4.4-forge
> ```
> 
> is the first error line that's thrown it's likely why it has been misdiagnosed as a Antique Atlas issue.
> 
> For this issue you either need to downgrade your Java 8 to something before update 321 or upgrade you Forge version to Forge 36.2.26 or greater.
> 
> [Found the fix here](https://github.com/McModLauncher/modlauncher/issues/91)
> 
> Hope this helps!

Thanks!

Someone that actually figured out the problem rather than just claiming there wasn't one!

Hopefully we can get the "minVersion" property fix to antiqueatlas.mixins.json
