### ISSUE TITLE
Crash on fabric 1.17.1 when right click with an atlas in hand

### ISSUE THREAD

**Issue by Zano1999** [Hunternif/AntiqueAtlas#406]
[22:59:02] [Server thread/INFO]: Sent Atlas #1 data to player Zano1999
[22:59:15] [Worker-Main-7/INFO]: Created new marker #1"Villaggio"@(-1012, 1322)
[22:59:23] [Render thread/INFO]: [STDOUT]: Minimap session finalized.
[22:59:23] [Server thread/INFO]: Zano1999 lost connection: Disconnesso/a
[22:59:23] [Server thread/INFO]: Zano1999 ha abbandonato la partita
[22:59:23] [Render thread/INFO]: [STDOUT]: Finalizing world map session...
[22:59:23] [Thread-239/INFO]: [STDOUT]: World map force-cleaned!
[22:59:23] [Server thread/INFO]: Stopping singleplayer server as player logged out
[22:59:23] [Render thread/INFO]: [STDOUT]: World map session finalized.
[22:59:23] [Server thread/INFO]: Stopping server
[22:59:23] [Server thread/INFO]: Saving players
[22:59:23] [Server thread/INFO]: Saving worlds
[22:59:23] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Test]'/minecraft:overworld
[22:59:23] [Server thread/INFO]: Saving local markers data to NBT
[22:59:23] [Server thread/INFO]: Saving local markers data to NBT
[22:59:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Test]'/barrenisles:barren_isles
[22:59:25] [Server thread/INFO]: ThreadedAnvilChunkStorage (Test (1)): All chunks are saved
[22:59:25] [Server thread/INFO]: ThreadedAnvilChunkStorage (barren_isles): All chunks are saved
[22:59:25] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[22:59:25] [Render thread/INFO]: Stopping worker threads
[22:59:25] [Render thread/INFO]: Destroying pipeline OVERWORLD
[22:59:27] [Render thread/FATAL]: Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.61) ~[?:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:883) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1112) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:217) [intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.7.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.7.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.7.jar:?]
Caused by: java.lang.IllegalAccessError: 'java.util.List hunternif.mc.impl.atlas.client.gui.GuiAtlas.getChildren()'
	at net.blay09.mods.craftingtweaks.client.CraftingTweaksClient.screenDrawn(CraftingTweaksClient.java:324) ~[craftingtweaks-fabric-13.0.0+0.jar:?]
	at net.blay09.mods.balm.event.client.BalmClientEvents.lambda$initializeScreenEvents$4(BalmClientEvents.java:82) ~[balm-fabric-1.1.0+0.jar:?]
	at net.fabricmc.fabric.impl.client.screen.ScreenEventFactory.lambda$createAfterRenderEvent$4(ScreenEventFactory.java:54) ~[1f900de5-ae80-4450-9396-9dba893a2172.jar:?]
	at net.minecraft.client.render.GameRenderer.handler$zjm000$onAfterRenderScreen(GameRenderer:3044) ~[?:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:874) ~[?:?]
	... 10 more
[22:59:27] [Render thread/INFO]: OpenGL debug message: id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Polygon modes for <face> are disabled in the current profile.'
[22:59:27] [Render thread/INFO]: OpenGL debug message: id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Polygon modes for <face> are disabled in the current profile.'
[22:59:27] [Render thread/FATAL]: Unreported exception thrown!
java.lang.IllegalAccessError: 'java.util.List hunternif.mc.impl.atlas.client.gui.GuiAtlas.getChildren()'
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.61) ~[?:?]
	at net.blay09.mods.craftingtweaks.client.CraftingTweaksClient.screenDrawn(CraftingTweaksClient.java:324) ~[craftingtweaks-fabric-13.0.0+0.jar:?]
	at net.blay09.mods.balm.event.client.BalmClientEvents.lambda$initializeScreenEvents$4(BalmClientEvents.java:82) ~[balm-fabric-1.1.0+0.jar:?]
	at net.fabricmc.fabric.impl.client.screen.ScreenEventFactory.lambda$createAfterRenderEvent$4(ScreenEventFactory.java:54) ~[1f900de5-ae80-4450-9396-9dba893a2172.jar:?]
	at net.minecraft.client.render.GameRenderer.handler$zjm000$onAfterRenderScreen(GameRenderer:3044) ~[?:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:874) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1112) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:217) [intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.7.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.7.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.7.jar:?]
[22:59:27] [Render thread/FATAL]: Minecraft ran into a problem! Report saved to: C:\Users\Nicolas\AppData\Roaming\.minecraft\crash-reports\crash-2021-11-14_22.59.27-client.txt
---- Minecraft Crash Report ----
 
----------------
C2ME Compatibility Module Notice: 
Do NOT report to mod authors if you encountered issues with the following mods: 
- charm@3.3.2
You can try disabling compatibility modules for these mods in "c2me-compat.toml" and try reproduce again. 
Or try reproduce without C2ME. 
----------------
 
// Who set us up the TNT?
 
Time: 14/11/21, 22:59
Description: Rendering screen
 
java.lang.IllegalAccessError: 'java.util.List hunternif.mc.impl.atlas.client.gui.GuiAtlas.getChildren()'
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.61)
	at net.blay09.mods.craftingtweaks.client.CraftingTweaksClient.screenDrawn(CraftingTweaksClient.java:324)
	at net.blay09.mods.balm.event.client.BalmClientEvents.lambda$initializeScreenEvents$4(BalmClientEvents.java:82)
	at net.fabricmc.fabric.impl.client.screen.ScreenEventFactory.lambda$createAfterRenderEvent$4(ScreenEventFactory.java:54)
	at net.minecraft.client.render.GameRenderer.handler$zjm000$onAfterRenderScreen(GameRenderer:3044)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:874)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1112)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- Head --
Thread: Render thread
Stacktrace:
	at net.blay09.mods.craftingtweaks.client.CraftingTweaksClient.screenDrawn(CraftingTweaksClient.java:324)
	at net.blay09.mods.balm.event.client.BalmClientEvents.lambda$initializeScreenEvents$4(BalmClientEvents.java:82)
	at net.fabricmc.fabric.impl.client.screen.ScreenEventFactory.lambda$createAfterRenderEvent$4(ScreenEventFactory.java:54)
	at net.minecraft.class_757.handler$zjm000$onAfterRenderScreen(class_757.java:3044)
 
-- Screen render details --
Details:
	Screen name: hunternif.mc.impl.atlas.client.gui.GuiAtlas
	Mouse location: Scaled: (240, 126). Absolute: (960.000000, 506.000000)
	Screen size: Scaled: (480, 254). Absolute: (1920, 1013). Scale factor of 4.000000
Stacktrace:
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.61)
	at java.lang.Thread.getStackTrace(Thread.java:1596)
	at net.minecraft.util.crash.CrashReportSection.trimStackTraceEnd(CrashReportSection:523)
	at net.minecraft.util.crash.CrashReport.addElement(CrashReport:198)
	at net.minecraft.world.World.addDetailsToCrashReport(World:845)
	at net.minecraft.client.world.ClientWorld.addDetailsToCrashReport(ClientWorld:370)
	at net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient:2399)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:747)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
 
-- Affected level --
Details:
	All players: 1 total; [class_746['Zano1999'/83, l='ClientLevel', x=-745.60, y=56.00, z=1528.31]]
	Chunk stats: 1024, 575
	Level dimension: minecraft:overworld
	Level spawn location: World: (80,76,240), Section: (at 0,12,0 in 5,4,15; chunk contains blocks 80,-128,240 to 95,511,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-128,0 to 511,511,511)
	Level time: 58450 game time, 1000 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:747)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
 
-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, charmonium/journeyman, Programmer Art, Better Enchantment Names (color-coded), Zano's Programmer Art.zip
 
-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.2, Eclipse Foundation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Foundation
	Memory: 2131409464 bytes (2032 MiB) / 4261412864 bytes (4064 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 3,40
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce RTX 2060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x1e89
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7196
	Memory slot #0 capacity (MB): 4096,00
	Memory slot #0 clockSpeed (GHz): 1,33
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096,00
	Memory slot #1 clockSpeed (GHz): 1,33
	Memory slot #1 type: DDR3
	Memory slot #2 capacity (MB): 4096,00
	Memory slot #2 clockSpeed (GHz): 1,33
	Memory slot #2 type: DDR3
	Memory slot #3 capacity (MB): 4096,00
	Memory slot #3 clockSpeed (GHz): 1,33
	Memory slot #3 type: DDR3
	Virtual memory max (MB): 18740,36
	Virtual memory used (MB): 13473,22
	Swap memory total (MB): 2432,00
	Swap memory used (MB): 58,23
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		antiqueatlas: Antique Atlas 6.1.1-fabric-mc1.17.1
		appleskin: AppleSkin mc1.17-2.1.3
		aqupdcaracal: Caracal mob 1.17-1.3.1
		aqupdgrizzly: Grizzly Bear mob 1.1.1
		architectury: Architectury 2.6.35
		armorhotswap: ArmorHotswap 1.1
		attachleadstologs: Attachleadstologs 1.0.0-1.17.1
		autofish: Autofish 0.9.3
		awesomedungeon: Awesome Dungeon 1.1.1
		awokenworld: Awoken World 2.0.0
		balm-fabric: Balm 1.1.0+0
		barrenisles: Barren Isles fabric-1.17-1.0.6
		bclib: BCLib 0.4.0
		bedrockify: BedrockIfy 1.2.0+mc1.17.1
		betterdungeons: YUNG's Better Dungeons 1.17-1.0.1
		betterendsky: BetterEnd Sky 2.0.0
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.0
		bettersafebed: BetterSafeBed fabric-1.17-1.4
		betterstrongholds: YUNG's Better Strongholds 1.17-1.0
		biome_locator: Biome Locator 1.1.2
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.5.0
		caelus: Caelus API 0.0.16-1.17
		cardinal-components-base: Cardinal Components API (base) 3.0.1
		cardinal-components-entity: Cardinal Components API (entities) 3.0.1
		cardinal-components-item: Cardinal Components API (items) 3.0.1
		carrier: Carrier 1.8.0
		celib: Celib - CebbyS Library Mod 0.5.0
		chalk: Chalk 1.0.2
		charm: Charm 3.3.2
		charmonium: Charmonium 3.3.0
		classicbeaches: Classic Beaches 0.3.1
		cleancut: CleanCut 1.17-4.0-fabric
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v5 5.0.38
		collective-fabric: Collective (Fabric) 1.51
		columns: Columns 1.2.0
		colytra: Colytra 2.0.0-1.17
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		complete_bone_meal: Complete Bone Meal 1.2.0
		connectiblechains: Connectible Chains 1.2.3
		cpas: cpas 2.0.0
		cpas-api: cpas-api 2.0.0
		cpas-runtime: cpas-runtime 2.0.0
		cpas-trinkets: cpas-trinkets 2.0.0
		craftingtweaks: Crafting Tweaks 13.0.0+0
		curses: Curses 1.6.0
		customskinloader: CustomSkinLoader 14.13-SNAPSHOT-278
		darkness: True Darkness 1.6.72
		dehydration: Dehydration 1.2.5
		doublejump: Double Jump Mod 1.0.0+mc1.17
		dungeons_arise: When Dungeons Arise 2.1.48-fabric
		earlygame: EarlyGame 1.17.x-1.1.1
		elytratrinket: Elytra Trinket 2.0.1-1.17
		enderscape: Enderscape 0.1.1
		environmentz: EnvironmentZ 1.1.7
		exdel: Explorer's Delight 1.0.0-alpha.4
		fabric: Fabric API 0.42.1+1.17
		fabric-api-base: Fabric API Base 0.4.0+5847535018
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+5847535018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.2+5847535018
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+5847535018
		fabric-command-api-v1: Fabric Command API (v1) 1.1.4+5847535018
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+5847535018
		fabric-containers-v0: Fabric Containers (v0) 0.1.13+5847535018
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.1+5847535018
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.6+5847535018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.13+5847535018
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.3.1+5847535018
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.11+5847535018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+5847535018
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.8+5847535018
		fabric-item-api-v1: Fabric Item API (v1) 1.2.5+5847535018
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+5847535018
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+5847535018
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.3+5847535018
		fabric-language-kotlin: Fabric Language Kotlin 1.6.4+kotlin.1.5.30
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.5+5847535018
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.5+5847535018
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.2+6d0fac4218
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.5+6d0fac4218
		fabric-models-v0: Fabric Models (v0) 0.3.1+5847535018
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.14+5847535018
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.12+5847535018
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+5847535018
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.11+6d0fac4218
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.5+6d0fac4218
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+5847535018
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.13+5847535018
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+5847535018
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.9+5847535018
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.6+6d0fac4218
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+5847535018
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.2.1+6d0fac4218
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.7+6d0fac4218
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.1+6d0fac4218
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.9+5847535018
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.5+5847535018
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.9+5847535018
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.14+5847535018
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.2+5847535018
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+5847535018
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.1+eb76084f18
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.1+6d0fac4218
		fabrication: Fabrication 2.0.0_01
		fabricloader: Fabric Loader 0.11.7
		fallingleaves: Falling Leaves 1.7.3+1.17.1
		fallingtree: FallingTree 2.14.1
		fiber: fiber 0.23.0-2
		flytre_lib: FlytreLib 0.2.14
		full_slabs: FullSlabs 3.2.1
		gbfabrictools: GBfabrictools 1.3.4+1.17
		geckolib3: Geckolib 3.0.26
		geodes: More Geodes 1.0.4
		grabcraft-downloader: GrabcraftLitematic 1.17-fabric0.34.9-0.4
		grindenchantments: Grind Enchantments 1.4.0+1.17.1
		guifollowers-fabric: GUI Followers (Fabric) 1.7
		hlandbukkit_c2me-fabric_ver_1_17_libs_: libs 0.2.0+alpha.5.0
		hookshot: Hookshot 22.0
		horsestatsvanilla: Horse Stats Vanilla 4.1.8
		illuminations: Illuminations 1.6.3
		improved-stations: Improved Stations 2.0.5
		infinitevillagertrading: InfiniteVillagerTrading 1.17-fabric0.34.9-1.1
		inventoryhotswap: Inventory Hotswap 1.2.0
		inventoryhud: Inventory HUD + 3.4.0
		inventoryprofilesnext: Inventory Profiles 0.7.4
		iris: Iris 1.1.2+build.9
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		lambdynlights: LambDynamicLights 2.0.2+1.17
		lapisreserve: Lapis Reserve 1.0.8
		letsleepingdogslie: Let Sleeping Dogs Lie - Fabric (Unofficial) 1.0.0
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.0.0-beta.4+1.17-rc1
		libninepatch: LibNinePatch 1.1.0
		litematica: Litematica 0.0.0-dev.20210616.033538
		lithium: Lithium 0.7.4
		loud_leads: Loud Leads 1.0.1+mc1.17
		maelstrom_library: Maelstrom Library 1.2.1-1.17-pre1
		magna: Magna 1.5.5-1.17-pre4
		malilib: MaLiLib 0.10.0+dev.22
		maptooltip: Map Tooltip 1.3.0
		maybe-data: Maybe data 1.0.1-1.17
		minecraft: Minecraft 1.17.1
		miniextras: Mini Extras Mod 1.3.2+1.17.1
		mm: Manningham Mills 2.3
		mobs_attempt_parkour: Mobs Attempt Parkour 0.2.3-1.17-pre1
		modmanager: Mod Manager 1.1.1-alpha+1.17
		modmenu: Mod Menu 2.0.13
		monsters_in_the_closet: Monsters in the Closet 1.0.2+1.17
		morebannerfeatures: More Banner Features 1.0.2
		mostructures: Mo' Structures 1.3.0-pre1-1.17.1
		noexpensive: NoExpensive 1.17-Fabric-1.2.0
		nopearldamage: No Pearl Damage! 1.1.0
		notenoughcrashes: Not Enough Crashes 3.7.0+1.17.1
		noweakattack: No Weak Attack 1.1.2
		observable: Observable 0.1.2-1.17
		odysseyhud: OdysseyHUD 1.0.0
		offhandoverhaul: Offhand Overhaul 1.2.0
		oldswing: Old Swing 3.0.1
		omega-config: OmegaConfig 1.0.8
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.30
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.2
		outvoted: Outvoted 1.5.0-b1
		paintings: Paintings ++ 1.17.1-1.0.0.3
		perorate: Perorate 1.2.0
		plated: Plated 2.1.1
		pride: Pride Lib 1.0.0+21w03a
		quickspyglasser: Quick Spyglasser 0.2.1
		randombonemealflowers-fabric: Random Bone Meal Flowers (Fabric) 1.5
		rare-ice: Rare Ice 0.3.0
		repurposed_structures: Repurposed Structures 2.5.2+1.17.1
		reroll: Reroll 1.3.0-1.17.1
		right-click-clear: Right Click Clear 2.0.3
		rightclickharvest: Right Click Harvest 1.3.0
		roughlyenoughitems: Roughly Enough Items 6.1.314-alpha
		scorch: Scorch 1.2.0
		secondchance: Second Chance 1.1.0
		shulkerboxtooltip: Shulker Box Tooltip 3.0.2+1.17.1
		sihywtcamc: sihywtcamc 1.3.1+1.17.1
		sihywtcamd: sihywtcamd 1.5+1.17.1
		snowundertrees: Snow Under Trees 1.0.0
		soaringstructures2: Soaring Structures 2 1.17.1 - 1.9.0
		sodium: Sodium 0.3.2+IRIS2-build.9
		spruceui: SpruceUI 3.2.0+1.17
		squirrels: Squirrels 1.1.0-1.17
		starlight: Starlight 1.0.0+fabric.73f6d37
		statement: Statement 4.1.3+1.14.4-1.17.1
		statement_vanilla_compatibility: Statement Vanilla Compatibility Module 1.0.1+1.16.5-1.17
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		stonevaults: Stonevaults 1.1.0
		strawgolem: Strawgolem 1.10-B3
		sulfurpotassiummod: Sulfur & Potassium 1.1.1
		taxfreelevels: Tax Free Levels 1.2
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 2.0.0
		terraform-config-api-v1: Terraform Config API (v1) 2.0.0
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 2.0.0
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 2.0.0
		terraform-tree-api-v1: Terraform Tree API (v1) 2.0.0
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		terrific_trinkets: Terrific Trinkets 0.2.0
		torohealth: ToroHealth Damage Indicators 1.17-fabric-7
		totemplus: Totem Plus 1.1
		traverse: Traverse 4.0.0
		trinketofundying: Trinket of Undying 2.0.0-1.17
		trinkets: Trinkets 3.0.4
		trinketshulkerboxes: Trinket Shulker Boxes 2.0.0-1.17
		trulytreasures: Truly Treasures 1.0
		vanilla-hammers: Vanilla Hammers 3.1.2-1.17
		vanillaexcavators: Vanilla Excavators 1.1.0
		waystones: Waystones 2.1.2
		wild_update: Wild Update 1.17.1-0.0.7
		windchimes: Windchimes 1.2.0
		woolstostring: AllWoolsToString 1.0.0
		worldedit: WorldEdit 7.2.7+9f3e795
		xaerominimap: Xaero's Minimap 21.15.1
		xaeroworldmap: Xaero's World Map 1.16.1
		xp_storage: XP Storage 1.4+1.17.1
		yigd: You're in Grave Danger 1.1.1
		yungsapi: YUNG's API 1.17-Fabric-16
	Launched Version: fabric-loader-0.11.7-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 2060/PCIe/SSE2 GL version 3.2.0 NVIDIA 471.96, NVIDIA Corporation
	Window size: 1920x1013
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, charmonium/journeyman, programer_art, file/Better Enchantment Names (color-coded) (incompatible), file/Zano's Programmer Art.zip
	Current Language: Italiano (Italia)
	CPU: 4x Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz
	Player Count: 1 / 8; [class_3222['Zano1999'/83, l='ServerLevel[Test]', x=-745.60, y=56.00, z=1528.31]]
	Data Packs: vanilla, file/Chicken_Shedding_1.1.zip (incompatible), file/DWAEBH+1.6.zip, file/Lumberjacks+ Ver 0.3 - TRUE SURVIVAL Datapack - Copy.zip, file/Tridents_o_Plenty_1.2.zip (incompatible), file/WallsOfConquest_ (1).zip (incompatible), file/Zano crafting pack.zip (incompatible), file/Zano lucky-block-datapack-v1-3-e40.zip (incompatible), file/armor statues v2.8.1.zip, file/classic fishing loot v1.1.0.zip, file/custom nether portals v2.3.2.zip, file/custom villager shops v1.2.0.zip, file/custom-trees-datapack-v1-2.zip (incompatible), file/fancy structures 1-6-6.zip (incompatible), file/fast leaf decay v2.0.3.zip, file/loot-table-PACK.zip (incompatible), file/pillager-settlements-e2230.zip (incompatible), file/pillager-stronghold-1-17.zip, file/spider-webbing-1565120589.zip (incompatible), file/tuco-s-overhauled-desert-pyramid-e1590.zip, file/unlock all recipes v2.0.1.zip, Fabric Mods
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Fabric Loader (fabricloader), Fabric Screen API (v1) (fabric-screen-api-v1), Crafting Tweaks (craftingtweaks), Balm (balm-fabric)

**Comment by tyra314** [comment]
I believe this is caused by the CraftingTweaks mod and should be reported to them.

**Comment by Zano1999** [comment]
I tested it and i can confirm is caused by an incompatibility between the 2 mods, for some reason with crafting tweaks installed it crash when i open the atlas at fullscreen

**Comment by tyra314** [comment]
There won't be another update for 1.17. Feel free to open a new issue if this also effects other versions.
